python vrepair_main.py \
    --load_pretrained_model \
    --model_name=fine_tuned_model.bin \
    --output_dir=./saved_models \
    --tokenizer_name=./bpe_tokenizer \
    --do_train \
    --train_data_file=../../data/cve_fixes_and_big_vul/train.csv \
    --eval_data_file=../../data/cve_fixes_and_big_vul/val.csv \
    --test_data_file=../../data/cve_fixes_and_big_vul/test.csv \
    --epochs 50 \
    --encoder_block_size 512 \
    --decoder_block_size 256 \
    --train_batch_size 32 \
    --eval_batch_size 32 \
    --learning_rate 1e-4 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456  2>&1 | tee train.log